In [2]:
import numpy as np


In [3]:
arr=np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr2d=arr.reshape((3,3))
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr2d.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr2d.flatten('F') # F:fotan

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [7]:
arr2d.flatten('c') # c style

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.linspace(1,3,100) # i

array([1.        , 1.02020202, 1.04040404, 1.06060606, 1.08080808,
       1.1010101 , 1.12121212, 1.14141414, 1.16161616, 1.18181818,
       1.2020202 , 1.22222222, 1.24242424, 1.26262626, 1.28282828,
       1.3030303 , 1.32323232, 1.34343434, 1.36363636, 1.38383838,
       1.4040404 , 1.42424242, 1.44444444, 1.46464646, 1.48484848,
       1.50505051, 1.52525253, 1.54545455, 1.56565657, 1.58585859,
       1.60606061, 1.62626263, 1.64646465, 1.66666667, 1.68686869,
       1.70707071, 1.72727273, 1.74747475, 1.76767677, 1.78787879,
       1.80808081, 1.82828283, 1.84848485, 1.86868687, 1.88888889,
       1.90909091, 1.92929293, 1.94949495, 1.96969697, 1.98989899,
       2.01010101, 2.03030303, 2.05050505, 2.07070707, 2.09090909,
       2.11111111, 2.13131313, 2.15151515, 2.17171717, 2.19191919,
       2.21212121, 2.23232323, 2.25252525, 2.27272727, 2.29292929,
       2.31313131, 2.33333333, 2.35353535, 2.37373737, 2.39393939,
       2.41414141, 2.43434343, 2.45454545, 2.47474747, 2.49494

In [9]:
arr2d.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

#### mathematical functions

In [10]:
arr1=np.arange(1,10).reshape((3,3))
arr2=np.arange(3,12).reshape((3,3))
arr1,arr2


(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]))

In [11]:
np.add(arr2,arr1)

array([[ 4,  6,  8],
       [10, 12, 14],
       [16, 18, 20]])

In [12]:
arr2 + arr1

array([[ 4,  6,  8],
       [10, 12, 14],
       [16, 18, 20]])

In [13]:
np.subtract(arr2,arr1)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [14]:
arr2 - arr1

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [15]:
np.multiply(arr1,arr2)

array([[ 3,  8, 15],
       [24, 35, 48],
       [63, 80, 99]])

In [16]:
arr1 * arr2

array([[ 3,  8, 15],
       [24, 35, 48],
       [63, 80, 99]])

In [17]:
np.divide(arr2,arr1)

array([[3.        , 2.        , 1.66666667],
       [1.5       , 1.4       , 1.33333333],
       [1.28571429, 1.25      , 1.22222222]])

In [18]:
arr2 / arr1

array([[3.        , 2.        , 1.66666667],
       [1.5       , 1.4       , 1.33333333],
       [1.28571429, 1.25      , 1.22222222]])

In [19]:
arr3=np.array([10,20,30])
arr3

array([10, 20, 30])

In [20]:
arr1 + arr3  # broadcasting

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

In [21]:
np.dot(arr1,arr2)

array([[ 42,  48,  54],
       [ 96, 111, 126],
       [150, 174, 198]])

In [22]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [23]:
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [24]:
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

In [25]:
np.concatenate([arr1 , arr2]) # no of colums should be same

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
arr1.min()

np.int64(1)

In [30]:
arr2.max()

np.int64(11)

In [31]:
arr2.argmax()

np.int64(8)

In [32]:
arr2.argmin()

np.int64(0)

In [27]:

np.concatenate([arr1,arr2],axis=1) #no of  rows should be same

array([[ 1,  2,  3,  3,  4,  5],
       [ 4,  5,  6,  6,  7,  8],
       [ 7,  8,  9,  9, 10, 11]])

### splitting

In [28]:
np.split(arr1 ,3 , axis=1) # you can split eq

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]