In [2]:
import numpy as np

In [49]:
np.random.random()

0.8319897677872526

In [5]:
team1=np.random.randint(0,36,20)
team1

array([11, 33, 19, 15,  2, 33, 28,  8,  0,  6,  2,  2,  0,  4,  9,  5, 22,
       25,  5, 13], dtype=int32)

In [15]:
np.random.randint(0,36,(4,5))

array([[24, 29,  8,  2, 10],
       [ 0,  3, 17, 32, 20],
       [12, 11, 23, 28,  0],
       [16, 23, 22, 35, 21]], dtype=int32)

In [61]:
np.random.seed(10)
np.random.randint(0,100,1)

array([9], dtype=int32)

In [37]:
np.random.rand()

0.6119433411110109

In [18]:
np.random.randn(10)

array([-2.93119247, -0.27828276,  0.29986131,  1.19449472, -0.90561048,
       -0.89808938,  0.45187984, -0.85947418, -0.53479453,  1.03287114])

In [67]:
dice=np.arange(1,7)

In [69]:
np.random.choice(dice,1)

array([5])

In [80]:
dice

array([1, 2, 3, 4, 5, 6])

In [76]:
np.random.permutation(dice)

array([4, 6, 3, 5, 1, 2])